feat: Add underage confirmation in extra_user_fields
OpenSourcePolitics/decidim-module-extra_user_fields pull request #3
Opened 2024-03-21 16:14 UTC by AyakorK

#### :tophat: Description

This feature adds an underage confirmation in extra user fields that is directly linked to the date of birth if it is activated with a configurable minimal age in the range of 15 to 21 , 

#### :pushpin: Related Issues
*Link your PR to an issue*
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-0-27-Ajout-d-une-option-autorisation-parentale-au-module-extra-sign-up-fields-97dbaea5c88b4fddbce1719ae66343e4?pvs=4)

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access BackOffice and access to EUF fields

##### 1st test : 
* Enable only the underage field
* Try to create an account 
* Check that there are two mails sent, the one for the user to confirm his account and the second one to the statutory representative that was mentioned
*
##### 2nd test : 
* Enable the underage field with the date of birth and configure the minimum age required
* Check that when you come to the page there is not any checkbox displayed
* Try to set a birth date and register your user
* If this is below it should appear and then be ticked automatically
* Otherwise it should not be displayed at all
* Try to register your user

##### Some use cases to test : 
* Try to change the birth date from an invalid to a valid one
* Try to untick the checkbox and see what happens (should not create the user) with an "invalid" birth date

#### Tasks
- [x] Add the field
- [x] Add some specs
- [x] Add a JS file to handle the signup field combinated to the date of birth one
- [x] Modify the user
- [x] Add some verifications and fix some tests that weren't done
- [x] Create a mailer to send the mail to the statutory representative
- [x] Backport the mail format from Toulouse

2024-03-25 10:20 UTC, luciegrau reviewed
Thanks Guillaume for your PR, which seems to work well and corresponds to the expected behavior for this feature! 

I just have one feedback before approving it: when I want to create an account as a minor user, fill in my date of birth and the parental authorization is already checked, if I uncheck it and try to finalize my registration, I get an error message telling me that I can't register (which is great). However, it seems that translations are missing from the warning message at the top of the page and from the authorization field (see below). 
<img width="1437" alt="Capture d’écran 2024-03-25 à 11 14 22" src="https://github.com/OpenSourcePolitics/decidim-module-extra_user_fields/assets/87868063/801908ab-3c5c-4d52-b83a-0100cfd8a2f0">
<img width="558" alt="Capture d’écran 2024-03-25 à 11 14 35" src="https://github.com/OpenSourcePolitics/decidim-module-extra_user_fields/assets/87868063/05f08820-c7ef-487b-a23e-b7f17ceca40e">

2024-03-25 13:52 UTC, luciegrau approved these changes

2024-03-26 15:23 UTC, Quentinchampenois requested changes
I have some changes but nice feature !

2024-03-26 15:23 UTC, Quentinchampenois commented on app/commands/concerns/decidim/extra_user_fields/create_registrations_commands_overrides.rb
> +        Decidim::ExtraUserFields::StatutoryRepresentativeMailer.inform(@user).deliver_now
To be homogeneous with `app/commands/concerns/decidim/extra_user_fields/omniauth_commands_overrides.rb:90` it should be 

```suggestion
        Decidim::ExtraUserFields::StatutoryRepresentativeMailer.inform(@user).deliver_later
```

2024-03-26 15:23 UTC, Quentinchampenois commented on app/controllers/decidim/extra_user_fields/extra_user_fields_controller.rb
> +          render json: { error: "Underage limit not found" }, status: :not_found
Should be a I18n key

2024-03-26 15:23 UTC, Quentinchampenois commented on app/forms/concerns/decidim/extra_user_fields/forms_definitions.rb
> +      def birth_date_under_limit
We should split this method into small ones. 

I wonder if we should move birth_date validations in a dedicated module to include but for now it should be goot

2024-03-26 15:23 UTC, Quentinchampenois commented on app/forms/decidim/extra_user_fields/admin/extra_user_fields_form.rb
> +          self.underage_limit = model.extra_user_fields.dig("underage", 18)
We should use a `config_accessor` on the module rather than hardcoded values

2024-03-26 15:23 UTC, Quentinchampenois commented on app/commands/decidim/extra_user_fields/admin/update_extra_user_fields.rb
> +            "underage_limit" => form.underage_limit || 18
We should use a `config_accessor` on the module rather than hardcoded values

2024-03-26 15:23 UTC, Quentinchampenois commented on app/packs/src/decidim/extra_user_fields/signup_form.js
> +    $.ajax({
Ajax request should be executed only if under_age is enabled

2024-03-26 15:23 UTC, Quentinchampenois commented on app/views/decidim/extra_user_fields/admin/extra_user_fields/fields/_underage.html.erb
> +    <%= form.select :underage_limit, (15..21).to_a, selected: current_organization.extra_user_fields[:underage_limit] || 18, label: t(".limit") %>
We should use a `config_accessor` on the module rather than hardcoded values

2024-03-26 15:24 UTC, Quentinchampenois commented on app/controllers/decidim/extra_user_fields/extra_user_fields_controller.rb
> +          render json: { error: "Underage limit not found" }, status: :not_found
Or maybe it shouldn't return a 404 but the default value *

2024-03-27 14:39 UTC, Quentinchampenois approved these changes

2024-03-27 14:39 UTC, merged