fix: Hotfixes about crashing issues on the new field
OpenSourcePolitics/decidim-module-extra_user_fields pull request #4
Opened 2024-03-27 15:45 UTC by AyakorK

Two thing fixes: 

- We couldn't modify back the extra user fields because .dig does not work for integers
- The underage limit was not fetched in the _underage.html.erb because I had put a wrong key.

2024-03-28 10:10 UTC, Quentinchampenois approved these changes

2024-03-28 14:26 UTC, Quentinchampenois requested changes
User can't update her account after registration because `Underage can't be blank`

2024-04-02 12:27 UTC, Quentinchampenois approved these changes

2024-04-02 14:37 UTC, luciegrau approved these changes

2024-04-02 14:37 UTC, merged